create table Mobie_list (
	id INT,
	movie_name VARCHAR(50),
	releaseYear INT,
	genre VARCHAR(50),
	rating INT
);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (1, 'Hands Off the Loot (Touchez pas au grisbi)', 2008, 'Crime|Drama|Thriller', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (2, 'Prime of Miss Jean Brodie, The', 2009, 'Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (3, 'Last Legion, The', 2006, 'Action|Adventure|Fantasy|War', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (4, 'Lovers, The (Les Amants)', 2004, 'Drama', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (5, 'Lone Wolf and Cub: White Heaven in Hell (Kozure ôkami: Jigoku e ikuzo! Daigorô)', 2018, 'Action|Drama|Fantasy', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (6, 'Diary of a Shinjuku Thief (Shinjuku dorobo nikki)', 2009, 'Comedy|Drama', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (7, 'Lineup, The', 2003, 'Crime|Drama|Film-Noir', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (8, 'Kokowääh', 2010, 'Comedy', 3);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (9, 'Sarah''s Key (Elle s''appelait Sarah)', 2000, 'Drama', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (10, 'Light It Up', 2004, 'Drama', 2);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (11, 'Stand and Deliver', 2016, 'Comedy|Drama', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (12, 'Ice Age: A Mammoth Christmas', 2008, 'Adventure|Animation|Children', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (13, 'Another You', 2021, 'Comedy', 2);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (14, 'Surf Ninjas', 2010, 'Comedy', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (15, 'Marvin''s Room', 2020, 'Drama', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (16, 'Song Remains the Same, The', 2007, 'Documentary|Musical', 3);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (17, 'Junior', 2012, 'Comedy|Sci-Fi', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (18, 'Resurrection', 2007, 'Drama|Fantasy', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (19, 'Great Escape: The Untold Story', 2012, 'Documentary|Drama|War', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (20, 'Kivski Freski', 2001, 'Drama', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (21, 'Carnage', 2001, 'Comedy|Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (22, 'Beyond the Law (Beyond the Law - Blue)', 2006, 'Comedy|Crime|Drama', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (23, 'Empire Falls', 2008, 'Drama|Romance', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (24, 'Babette''s Feast (Babettes gæstebud)', 2018, 'Drama', 2);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (25, 'Backtrack (Catchfire)', 2016, 'Action|Drama|Thriller', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (26, 'Enduring Love', 2005, 'Drama', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (27, 'Seducing Mr. Perfect', 2017, 'Romance', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (28, 'Android', 2006, 'Sci-Fi', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (29, 'Good Morning, Night (Buongiorno, notte)', 2017, 'Drama', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (30, 'Poor Us: An Animated History of Poverty', 2013, 'Animation|Documentary', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (31, 'Whoopi Goldberg Presents Moms Mabley', 2004, 'Documentary', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (32, 'Pulse', 2007, 'Horror|Sci-Fi|Thriller', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (33, 'Jodhaa Akbar', 2012, 'Drama|Musical|Romance|War', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (34, 'Salon Kitty', 2021, 'Drama', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (35, 'Meet the Robinsons', 2010, 'Action|Adventure|Animation|Children|Comedy|Sci-Fi', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (36, 'Champion, The', 2002, 'Comedy', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (37, 'Great Bank Hoax, The', 2021, 'Comedy|Crime', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (38, 'Unspeakable Acts ', 2021, 'Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (39, 'Rails & Ties', 2010, 'Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (40, 'She Wore a Yellow Ribbon', 2002, 'Western', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (41, 'Boxtrolls, The', 2003, 'Adventure|Animation|Children|Comedy|Fantasy', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (42, 'Caddyshack', 2003, 'Comedy', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (43, 'Westbound', 2002, 'Western', 2);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (44, 'Southern Comfort', 2012, 'Drama|Thriller|War', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (45, 'Sherlock Holmes in Pearl of Death (Pearl of Death, The)', 2018, 'Crime|Horror|Mystery|Thriller', 3);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (46, 'Ward, The', 2010, 'Horror|Thriller', 3);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (47, 'Return of the Living Dead, The', 2005, 'Comedy|Horror|Sci-Fi', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (48, 'Kinbaku', 2005, 'Documentary', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (49, 'Until the End of the World (Bis ans Ende der Welt)', 2014, 'Adventure|Drama|Sci-Fi', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (50, 'Backwood Philosopher (Havukka-ahon ajattelija)', 2006, 'Comedy|Drama', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (51, 'Shadow of a Doubt', 2021, 'Crime|Drama|Thriller', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (52, 'Secret Adventures of Gustave Klopp, The (Narco)', 2021, 'Action|Comedy|Fantasy', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (53, 'In the Year of the Pig', 2014, 'Documentary|War', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (54, 'In Bed (En la cama)', 2007, 'Drama', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (55, 'Rhapsody in Blue', 2013, 'Drama|Musical', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (56, 'Bonsái', 2001, 'Drama', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (57, 'Experience Preferred... But Not Essential', 2016, 'Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (58, 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les)', 2005, 'Drama|Musical|Romance', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (59, 'Dragon Ball GT: A Hero''s Legacy (Doragon bôru GT: Gokû gaiden! Yûki no akashi wa sû-shin-chû)', 2019, 'Action|Adventure|Animation', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (60, 'Alan & Naomi', 2000, 'Children|Drama', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (61, 'Weekend', 2008, 'Drama|Romance', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (62, '7th Heaven (Seventh Heaven)', 2020, 'Drama|Romance', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (63, 'Burning, The', 2007, 'Horror', 8);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (64, 'Battle of the Rails, The (La bataille du rail)', 2019, 'Drama|War', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (65, 'Special Day, A (Giornata particolare, Una)', 2010, 'Drama|War', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (66, 'Man of La Mancha', 2003, 'Adventure|Comedy|Musical', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (67, 'The Nutcracker in 3D', 2014, 'Action|Children|Fantasy|Musical', 2);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (68, 'Bad Family (Paha Perhe)', 2015, 'Comedy|Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (69, 'Pick-up Summer (Pinball Summer)', 2002, 'Comedy', 2);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (70, 'Clown', 2000, 'Drama|Horror', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (71, 'The Kiss of Her Flesh', 2011, 'Horror|Thriller', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (72, 'Twist of Faith', 2016, 'Documentary', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (73, 'Casino', 2017, 'Crime|Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (74, 'Nomi Song, The', 2010, 'Documentary|Musical', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (75, 'Fort Apache, the Bronx', 2021, 'Action|Drama', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (76, 'Slappy and the Stinkers', 2000, 'Children|Comedy', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (77, 'Run for Cover', 2021, 'Western', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (78, 'Finding Normal', 2010, 'Comedy|Romance', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (79, 'I''m All Right Jack', 2009, 'Comedy', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (80, 'Stitches', 2006, 'Comedy|Horror', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (81, 'Cookout, The', 2007, 'Comedy', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (82, 'Scout, The', 2016, 'Comedy|Drama', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (83, 'Story of Temple Drake, The', 2000, 'Drama', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (84, 'Jauja', 2014, 'Drama|Western', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (85, 'Rear Window', 2002, 'Mystery|Thriller', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (86, 'How to Succeed in Business Without Really Trying', 2006, 'Comedy|Musical', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (87, 'Mexican Hayride', 2005, 'Comedy', 3);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (88, 'Offside', 2003, 'Comedy|Drama', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (89, 'Nice Guy Johnny', 2002, 'Comedy|Romance', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (90, 'Dry Cleaning (Nettoyage à sec)', 2007, 'Drama', 4);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (91, '11th Hour, The', 2007, 'Documentary', 7);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (92, 'American Swing', 2010, 'Documentary', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (93, 'Crossover', 2002, 'Action|Drama', 3);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (94, 'Calendar Girl', 2020, 'Comedy|Drama', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (95, 'Carrie', 2009, 'Drama|Horror', 5);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (96, 'Evil That Men Do, The', 2000, 'Action|Thriller', 1);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (97, 'Gamera vs. Guiron', 2014, 'Action|Adventure', 10);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (98, 'Once Upon a Time in Mexico', 2011, 'Action|Adventure|Crime|Thriller', 6);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (99, 'Sum of All Fears, The', 2010, 'Drama|Thriller', 9);
insert into Mobie_list (id, movie_name, releaseYear, genre, rating) values (100, 'Film with Me in It, A', 2006, 'Comedy|Thriller', 3);
